import { fmt } from "@m4rsh/cones";
import { converter, formatHex } from "culori";

const toOklch = converter("oklch");

const LANGUAGE_NAMES = {
  embedded: "javascript_embedded",
};

const BASE_NAMES = {
  goldenYellow: "golden_yellow",
  stringGray: "string_gray",
};
const luaBaseName = key => BASE_NAMES[key]
  ?? key.replace(/[A-Z]/g, letter => `_${letter.toLowerCase()}`);

const LUA_KEYWORDS = new Set([
  "and", "break", "do", "else", "elseif", "end", "false", "for", "function",
  "goto", "if", "in", "local", "nil", "not", "or", "repeat", "return", "then",
  "true", "until", "while",
]);

const luaString = value => JSON.stringify(value);
const luaKey = key => /^[A-Za-z_][A-Za-z0-9_]*$/.test(key) && !LUA_KEYWORDS.has(key)
  ? key
  : `[${luaString(key)}]`;
const hex = value => formatHex(value).toUpperCase();

function luaTable(value) {
  const entries = Object.entries(value).map(([key, entry]) => fmt`
    ${luaKey(key)} = ${typeof entry === "object" && entry !== null
      ? luaTable(entry)
      : luaString(entry)},
  `);
  return fmt`
    {
      ${entries.join("\n")}
    }
  `;
}

export function themeId(name) {
  return name
    .toLowerCase()
    .replace(/^argiope\s+/, "")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "") || "custom";
}

export function neovimAdapter(theme, { extends: parent } = {}) {
  const background = toOklch(theme.base.bg)?.l >= 0.6 ? "light" : "dark";
  const base = Object.fromEntries(
    Object.entries(theme.base.all).filter(([, color]) => color).map(([key, color]) => [
      luaBaseName(key),
      hex(color),
    ]),
  );
  const languages = Object.fromEntries(theme.languageEntries.map(([key, language]) => {
    const colors = Object.fromEntries(
      Object.entries(language.colors).map(([shade, color]) => [shade, hex(color)]),
    );
    return [LANGUAGE_NAMES[key] ?? key, { colors, roles: { ...language.tokens } }];
  }));

  return {
    name: theme.name,
    ...(parent ? { extends: parent } : {}),
    background,
    base,
    languages,
  };
}

export function neovimDefinitionLua(theme, options = {}) {
  return String(luaTable(neovimAdapter(theme, options)));
}

export function neovimSetupLua(theme, { id = themeId(theme.name), extends: parent } = {}) {
  return String(fmt`
    require("argiope").setup({
      theme = {
        variant = ${luaString(id)},
        definitions = {
          ${luaKey(id)} = ${neovimDefinitionLua(theme, { extends: parent })},
        },
      },
    })
  `);
}

export function neovimBuiltinsLua(entries) {
  const definitions = Object.fromEntries(
    entries.map(({ id, theme }) => [id, neovimAdapter(theme)]),
  );
  return String(fmt`
    -- Generated by argiope-palettes. Do not edit by hand.
    return {
      schema = 1,
      themes = ${luaTable(definitions)},
    }
  `);
}
