import { mkdir, readFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import {
  validateZedThemeFamily,
  zedThemeFamily,
  zedThemeJson,
} from "../src/adapters/zed.js";
import { DEFAULT_THEMES } from "../src/defaults.js";

const root = resolve(import.meta.dir, "..");
const output = resolve(root, "dist", "zed");
const upstream = resolve(root, "src", "zed", "upstream");

const languageSpecs = {
  // Grammar keys must match Tree-sitter's exported C symbols. Several
  // Argiope language identities can safely share the same parser.
  javascript: { directory: "argiope-javascript", grammar: "tsx", source: "javascript", name: "Argiope JavaScript", lineComments: ["// "] },
  embedded: { directory: "argiope-javascript-embedded", grammar: "tsx", source: "javascript", name: "Argiope Embedded JavaScript", lineComments: ["// "] },
  html: { directory: "argiope-html", grammar: "html", source: "html", name: "Argiope HTML" },
  svg: { directory: "argiope-svg", grammar: "html", source: "html", name: "Argiope SVG" },
  css: { directory: "argiope-css", grammar: "css", source: "css", name: "Argiope CSS", lineComments: ["/* "] },
  markdown: { directory: "argiope-markdown", grammar: "markdown", source: "markdown", name: "Argiope Markdown" },
  glsl: { directory: "argiope-glsl", grammar: "glsl", source: "glsl", name: "Argiope GLSL", lineComments: ["// "] },
  wgsl: { directory: "argiope-wgsl", grammar: "wgsl", source: "wgsl", name: "Argiope WGSL", lineComments: ["// "] },
};

const wgsl = {
  // This grammar does not expose comments, unlike the GLSL grammar. Keep the
  // query to nodes guaranteed by its pinned node-types.json so an optional
  // shader parser never prevents the rest of the extension from loading.
  highlights: `(ident) @variable
(int_literal) @number
(float_literal) @number
(bool_literal) @constant
(function_header
  (ident) @function)
(type_decl
  (ident) @type)
(attribute
  (ident) @attribute)
`,
  indents: `(compound_statement
  (brace_left)
  (brace_right) @end) @indent
`,
};

const fixedInjections = [
  ["svg", "argiope-svg"],
  ["md", "argiope-markdown"],
  ["glsl", "argiope-glsl"],
  ["wgsl", "argiope-wgsl"],
].map(([tag, language]) => `(call_expression
  function: (identifier) @_argiope_tag
  arguments: (template_string
    (string_fragment) @injection.content)
  (#eq? @_argiope_tag "${tag}")
  (#set! injection.language "${language}"))`).join("\n\n");

const rawJavaScriptInjection = `(call_expression
  function: (member_expression
    object: (identifier) @_argiope_raw
    property: (property_identifier) @_argiope_member)
  arguments: (template_string
    (string_fragment) @injection.content)
  (#eq? @_argiope_raw "raw")
  (#eq? @_argiope_member "js")
  (#set! injection.language "argiope-javascript-embedded"))`;

const write = async (path, content) => {
  await mkdir(dirname(path), { recursive: true });
  await Bun.write(path, content);
};

const capturesFor = query => [...new Set(
  [...query.matchAll(/@([A-Za-z_][A-Za-z0-9_.]*)/g)]
    .map(([, capture]) => capture)
    .filter(capture => !capture.startsWith("_")),
)];

const namespaceHighlights = (query, language) => query.split("\n").map(line => {
  // Captures appearing in predicates are predicate arguments, not query
  // captures. Rewriting those would turn `#eq?` and `#match?` invalid.
  if (line.includes("(#")) return line;
  let quoted = false;
  let escaped = false;
  let output = "";
  for (let index = 0; index < line.length; index += 1) {
    const character = line[index];
    if (character === '"' && !escaped) quoted = !quoted;
    escaped = character === "\\" && !escaped;
    if (!quoted && character === "@") {
      const match = line.slice(index).match(/^@([A-Za-z_][A-Za-z0-9_.]*)/);
      if (match) {
        const [capture, name] = match;
        output += name.startsWith("_") ? capture : `${capture} @argiope.${language}.${name}`;
        index += capture.length - 1;
        continue;
      }
    }
    output += character;
  }
  return output;
}).join("\n");

const configToml = spec => [
  "# Generated by argiope-palettes. Do not edit by hand.",
  `name = "${spec.name}"`,
  `grammar = "${spec.grammar}"`,
  "# This language is opt-in to avoid replacing Zed's bundled JavaScript.",
  "path_suffixes = []",
  "tab_size = 2",
  ...(spec.lineComments ? [`line_comments = [${spec.lineComments.map(JSON.stringify).join(", ")}]`] : []),
  "",
].join("\n");

const upstreamQuery = async (source, type) => source === "wgsl"
  ? wgsl[type]
  : readFile(resolve(upstream, source, `${type}.scm`), "utf8");

const javascriptInjections = async () => {
  const source = await readFile(resolve(upstream, "javascript", "injections.scm"), "utf8");
  return `${source
    .replace(
      "arguments: (template_string) @injection.content\n  (#set! injection.language \"html\"))",
      "arguments: (template_string\n    (string_fragment) @injection.content)\n  (#set! injection.language \"html\"))",
    )
    .replaceAll('(#set! injection.language "css")', '(#set! injection.language "argiope-css")')
    .replaceAll('(#set! injection.language "html")', '(#set! injection.language "argiope-html")')
    .replaceAll('(#set! injection.language "javascript")', '(#set! injection.language "argiope-javascript-embedded")')
    .replaceAll('(#set! injection.language "glsl")', '(#set! injection.language "argiope-glsl")')
    .replaceAll('(#set! injection.language "WGSL/WESL")', '(#set! injection.language "argiope-wgsl")')}

${fixedInjections}

${rawJavaScriptInjection}
`;
};

const capturesByLanguage = {};
for (const [language, spec] of Object.entries(languageSpecs)) {
  const highlights = await upstreamQuery(spec.source, "highlights");
  capturesByLanguage[language] = capturesFor(highlights);
  await write(resolve(output, "languages", spec.directory, "config.toml"), configToml(spec));
  await write(
    resolve(output, "languages", spec.directory, "highlights.scm"),
    `; Generated by argiope-palettes from Zed ${"53dbfe407328b2668d1114075ca3768dd1c2a2a5"}.\n${namespaceHighlights(highlights, language)}`,
  );
  await write(
    resolve(output, "languages", spec.directory, "indents.scm"),
    `; Generated by argiope-palettes.\n${await upstreamQuery(spec.source, "indents")}`,
  );
}
await write(
  resolve(output, "languages", languageSpecs.javascript.directory, "injections.scm"),
  `; Generated by argiope-palettes.\n${await javascriptInjections()}`,
);

const family = validateZedThemeFamily(zedThemeFamily(DEFAULT_THEMES, { capturesByLanguage }));
await write(resolve(output, "themes", "argiope.json"), zedThemeJson(DEFAULT_THEMES, { capturesByLanguage }));
console.log(`Wrote ${output} (${family.themes.length} themes)`);
