export const TOKEN_MAPS = {
  javascript: { 
    plain: "main",
    variable: "main",
    property: "soft",
    constant: "bright",
    string: "muted",
    escape: "bright",
    number: "accent",
    type: "light",
    function: "accent",
    call: "bright",
    operator: "soft",
    keyword: "gray_warm",
    control: "bright",
    return: "light",
    punctuation: "gray",
    bracket: "gray_dim",
    comment: "gray_dim" 
  },
  html: { 
    plain: "light",
    variable: "main",
    property: "main",
    constant: "accent",
    string: "light",
    escape: "accent",
    number: "accent",
    type: "main",
    function: "accent",
    call: "accent",
    operator: "accent",
    keyword: "muted",
    control: "accent",
    return: "accent",
    punctuation: "darkest",
    bracket: "darkest",
    comment: "muted" 
  },
  css: {
    plain: "main",
    variable: "main",
    property: "main",
    constant: "accent",
    string: "muted",
    escape: "accent",
    number: "accent",
    type: "main",
    function: "accent",
    call: "accent",
    operator: "main",
    keyword: "main",
    control: "accent",
    return: "accent",
    punctuation: "gray_dim",
    bracket: "muted",
    comment: "muted" 
  },
  markdown: {
    plain: "main",
    variable: "main",
    property: "soft",
    constant: "accent",
    string: "muted",
    escape: "accent",
    number: "accent",
    type: "main",
    function: "main",
    call: "light",
    operator: "main",
    keyword: "main",
    control: "accent",
    return: "accent",
    punctuation: "muted",
    bracket: "darkest",
    comment: "muted" 
  },
};

export const VERSICOLOR_TOKENS = {
  plain: "fg",
  variable: "beige",
  property: "beige",
  constant: "goldenYellow",
  string: "stringGray",
  escape: "orange",
  number: "purple",
  type: "cyan",
  function: "green",
  call: "green",
  operator: "pink",
  keyword: "pink",
  control: "pink",
  return: "pink",
  punctuation: "fg",
  bracket: "fg",
  comment: "comment",
};

export const CAPTURE_NAMES = {
  plain: "@none",
  variable: "@variable",
  property: "@property",
  constant: "@constant",
  string: "@string",
  escape: "@string.escape",
  number: "@number",
  type: "@type",
  function: "@function",
  call: "@function.call",
  operator: "@operator",
  keyword: "@keyword",
  control: "@keyword.conditional",
  return: "@keyword.return",
  punctuation: "@punctuation.delimiter",
  bracket: "@punctuation.bracket",
  comment: "@comment",
};
